//
//  TestExceptions.swift
//  MsgpackSerializationTests iOS
//
//  Created by cherrywoods on 21.02.18.
//
//  These tests are similar to the ExceptionTests from msgpack-cli
//  The expected msgpack values were partially generated by msgpack-tools
//  (https://github.com/ludocode/msgpack-tools)
//

import XCTest
@testable import MsgpackSerialization

class Exceptions: XCTestCase {

    func testInvalidMsgpack() {
        
        // test variants of invalid msgpack
        
        // empty data just isn't valid msgpack
        TestUtilites.testDecodeFailure(of: Data(), type: String.self)
        // c1 is an unused header in msgpack
        TestUtilites.testDecodeFailure(of: [0xc1], type: Int.self)
        // byte array contains one byte less then expected
        TestUtilites.testDecodeFailure(of: [0xa3, 0x61, 0x62], type: String.self)
        
    }
    
}
