//
//  TestTimestamp.swift
//  MsgpackSerializationTests iOS
//
//  Created by cherrywoods on 23.02.18.
//
//  These tests are similar to Tests from msgpack-cli
//  The expected msgpack values were partially generated by msgpack-tools
//  (https://github.com/ludocode/msgpack-tools)
//

import XCTest
@testable import MsgpackSerialization

class TimestampEncoding: XCTestCase {
    
    func testTimestamp32() {
        
        let date1 = Date(timeIntervalSince1970: 7)
        let date2 = Date(timeIntervalSince1970: 1042)
        
        TestUtilites.testRoundTrip(of: date1, expected: [0xd6, 0xff, 0x00, 0x00, 0x00, 0x07])
        TestUtilites.testRoundTrip(of: date2, expected: [0xd6, 0xff, 0x00, 0x00, 0x04, 0x12])
        
    }
    
    func testTimestamp64() {
        
        let date1 = Date(timeIntervalSince1970: 0.5)
        let date2 = Date(timeIntervalSince1970: 9_000.125)
        
        //                             the separation between nanoseconds and seconds is here |
        TestUtilites.testRoundTrip(of: date1, expected: [0xd7, 0xff, 0x77, 0x35, 0x94, 0b00000000, 0x00, 0x00, 0x00, 0x00])
        TestUtilites.testRoundTrip(of: date2, expected: [0xd7, 0xff, 0x1d, 0xcd, 0x65, 0b00000000, 0x00, 0x00, 0x23, 0x28])
        
    }
    
    func testTimestamp96() {
        
        let date1 = Date(timeIntervalSince1970: -1)
        let date2 = Date(timeIntervalSince1970: -1.5)
        let date3 = Date(timeIntervalSince1970: -62135596801)
        
        TestUtilites.testRoundTrip(of: date1, expected: [0xc7, 12, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff])
        
        TestUtilites.testRoundTrip(of: date2, expectedLength: 15)
        TestUtilites.testRoundTrip(of: date3, expectedLength: 15)
        
    }
    
}
