//
//  TestIntegerEncoding.swift
//  MsgpackSerializationTests iOS
//
//  Created by cherrywoods on 19.02.18.
//
//  These tests are similar to Tests from msgpack-cli
//  The expected msgpack values were partially generated by msgpack-tools
//  (https://github.com/ludocode/msgpack-tools)
//

import XCTest
@testable import MsgpackSerialization

class IntegerEncoding: XCTestCase {
    
    // test positive and negative fixnum
    func testSingleByteInts() {
        
        TestUtilites.testRoundTrip(of: 0, expected: [0] )
        TestUtilites.testRoundTrip(of: 127, expected: [0x7f])
        
        TestUtilites.testRoundTrip(of: -1, expected: [0xff])
        TestUtilites.testRoundTrip(of: -32, expected: [0xe0])
        
    }
    
    // test int8 and uint8
    func test2ByteInts() {
        
        TestUtilites.testRoundTrip(of: 128, expected: [0xcc, 0x80])
        TestUtilites.testRoundTrip(of: 207, expected: [0xcc, 0xcf])
        TestUtilites.testRoundTrip(of: UInt8.max /* 255 */, expected: [0xcc, 0xff])
        
        TestUtilites.testRoundTrip(of: -33, expected: [0xd0, 0xdf])
        TestUtilites.testRoundTrip(of: -99, expected: [0xd0, 0x9d])
        TestUtilites.testRoundTrip(of: Int8.min /* -128 */, expected: [0xd0, 0x80])
        
    }
    
    // test int16 and uint16
    func test3ByteInts() {
        
        TestUtilites.testRoundTrip(of: 256, expected: [0xcd, 0x01, 0x00])
        TestUtilites.testRoundTrip(of: 10743, expected: [0xcd, 0x29, 0xf7])
        TestUtilites.testRoundTrip(of: UInt16.max /* 65_535 */, expected: [0xcd, 0xff, 0xff])
        
        TestUtilites.testRoundTrip(of: -129, expected: [0xd1, 0xff, 0x7f])
        TestUtilites.testRoundTrip(of: -20111, expected: [0xd1, 0xb1, 0x71])
        TestUtilites.testRoundTrip(of: Int16.min /* -32_768 */, expected: [0xd1, 0x80, 0x00])
        
    }
    
    // test int32 and uint32
    func test5ByteInts() {
        
        TestUtilites.testRoundTrip(of: 65_536, expected: [0xce, 0x00, 0x01, 0x00, 0x00])
        TestUtilites.testRoundTrip(of: 2_000_000_001, expected: [0xce, 0x77, 0x35, 0x94, 0x01])
        TestUtilites.testRoundTrip(of: UInt32.max /* 4_294_967_295 */, expected: [0xce, 0xff, 0xff, 0xff, 0xff])
        
        TestUtilites.testRoundTrip(of: -32_769, expected: [0xd2, 0xff, 0xff, 0x7f, 0xff])
        TestUtilites.testRoundTrip(of: -2_000_000_001, expected: [0xd2, 0x88, 0xca, 0x6b, 0xff])
        TestUtilites.testRoundTrip(of: Int32.min /* -2_147_483_648 */, expected: [0xd2, 0x80, 0x00, 0x00, 0x00])
        
    }
    
    // test int64 and uint64
    func test9ByteInts() {
        
        TestUtilites.testRoundTrip(of: 4_294_967_296, expected: [0xcf, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,0x00])
        TestUtilites.testRoundTrip(of: 24_687_554_234_999_356, expected: [0xcf, 0x00, 0x57, 0xb5, 0x33, 0x24, 0x8c, 0xe2,0x3c])
        TestUtilites.testRoundTrip(of: UInt64.max /* 18_446_744_073_709_551_615 */, expected: [0xcf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,0xff])
        
        TestUtilites.testRoundTrip(of: -2_147_483_649, expected: [0xd3, 0xff, 0xff, 0xff, 0xff, 0x7f, 0xff, 0xff,0xff])
        TestUtilites.testRoundTrip(of: -77_900_325_776_243_886, expected: [0xd3, 0xfe, 0xeb, 0x3e, 0x11, 0x02, 0x38, 0x43,0x52])
        TestUtilites.testRoundTrip(of: Int64.min /* -9_223_372_036_854_775_808 */, expected: [0xd3, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,0x00])
        
    }
    
}
