//
//  TestDataEncoding.swift
//  MsgpackSerializationTests iOS
//
//  Created by cherrywoods on 22.02.18.
//
//  These tests are similar to Tests from msgpack-cli
//  The expected msgpack values were partially generated by msgpack-tools
//  (https://github.com/ludocode/msgpack-tools)
//

import XCTest
@testable import MsgpackSerialization

class DataEncoding: XCTestCase {
    
    func testBin8Format() {
        
        let two240Times = Data(repeating: 2, count: 240)
        let expectedForA240Times = Data(bytes: [0xc4, 240]) + Data(repeating: 0x02, count: 240)
        TestUtilites.testRoundTrip(of: two240Times, expected: expectedForA240Times)
        
    }
    
    func testBin16Format() {
        
        // from now on just test for the right length of the msgpack data
        let tenThousandOnes = Data(repeating: 1, count: 40_000)
        // the expected length is 3 (header + length) + 40_000
        TestUtilites.testRoundTrip(of: tenThousandOnes, expectedLength: 40_003)
        
    }
    
    func testBin32Format() {
        
        // this test will take some time...
        let manyManyFours = Data(repeating: 4, count: 70_000)
        // the expected length is 5 (header + length) + 70_000
        TestUtilites.testRoundTrip(of: manyManyFours, expectedLength: 70_005)
        
    }
    
}

